---
title: "Covid-19 Colombia"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
#http://www.briansarnacki.com/an-easy-way-to-map-data-in-r-with-plotly/
# pagina para mapas 
library(flexdashboard) # construccion de tableros
library(sf)
library(ggplot2) # paquete de graficos
library(tmap)
library(tmaptools)
library(leaflet)
library(dplyr)
library(rgdal)
library(sp)
library(readxl)

require(raster)
library(RSocrata)
library(DT)
library(mapview)

token <- "ew2rEMuESuzWPqMkyPfOSGJgE"
df.ins <- read.socrata("https://www.datos.gov.co/resource/gt2j-8ykr.json", app_token = token)
mapa=readOGR("~/R/Proyecto Natalia/depto/depto.shp",stringsAsFactors=FALSE)
 write.csv(df.ins, file = "df.ins.csv")
```

Column {data-width=600}
-----------------------------------------------------------------------

### Reporte a la fecha

```{r}
df.ins$codigo=NA
df.ins$codigo=trunc(as.numeric(df.ins$c_digo_divipola)/1000)
tabla=table(df.ins$codigo,df.ins$atenci_n)
rownames(tabla)=c("Antioquia",
    "Atlantico",
    "Bogota D.C",
    "Bolivar", 
    "Boyaca",
    "Caldas",
    "Caquetá",
    "Cauca",
    "Cesar",
    "Cordoba",
    "Cundinamarca",
    "Chocó", 
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta", 
    "Nariño",
    "Norte De Santander",  
    "Quindio",
    "Risaralda", 
    "Santander",
    "Sucre", 
    "Tolima",
    "Valle del Cauca",
    "Arauca",
    "Casanare",
    "Putumayo",
    "Amazonas",     
    "Guainia",
    "Guaviare",
    "Vaupes",
    "Vichada", 
    "San Andres P.y Sta C.")
colnames(tabla)=c("En casa", "Fallec.", "Hospital.", "En UCI", "NA", "Recuperados")
 tabla
 write.csv(tabla, file = "taba.csv")
```

Column {data-width=650} 
-----------------------------------------------------------------------

### Fallecidos por departamento 

```{r}

mapa$casa=tabla[,1]
mapa$fall=tabla[,2]
mapa$hosp=tabla[,3]
mapa$uci=tabla[,4]
mapa$recup=tabla[,6]
mapa$inf=tabla[,1]+tabla[,3]+tabla[,4]+tabla[,5]
# col <- rev(heat.colors(26))
# spplot(mapa[,7],
#       col.regions=col)
mapview(mapa[,7])

```


```{r}

plot_ly(data=mapa)

```

